options:
    name: couette
    save_ani: 0
    maxIt: 3000
    plot_dim: 1
    plotInterval: 1
    writeOutput: 0
    writeField: 0
geometry:
    Lx: 1.e-3
    Ly: 1.e-3
    h1: 1.e-6
    h2: 1.e-6
numerics:
    Nx: 50
    Ny: 3
    dt: 1.e-8
material:
    mu: 1e-2
#    mu: 0.16268
BC:
    U: -0.1
    V: 0.
    P0: 101325.
    rho0: 877.7007
    temp: 292
