options:
    name: inclined
    plotDim: 1
    plotOption: 0
    plotInterval: 1
    writeOutput: 1
    writeInterval: 10
disc:
    Lx: 1.e-3
    Ly: 1.e-3
    Nx: 50
    Ny: 50
geometry:
    h1: 2.2e-6
    h2: 1.e-6
    U: 0.1
    V: 0.
numerics:
    dt: 1.e-12
    maxIt: 100
    numFlux: FW
    freq: 1
    periodicX: 0
    periodicY: 1
material:
    mu: 0.0794
    P0: 101325
    rho0: 877.7007
    T0: 323.15
    s: 0
