options:
    name: journal
    plotDim: 1
    plotOption: 0
    plotInterval: 1
    writeOutput: 1
    writeInterval: 10
disc:
    Lx: 1.e-3
    Ly: 1.e-3
    Nx: 50
    Ny: 50
geometry:
    h1: 1.e-6
    h2: 2.2e-6
    ex: 0.8
    U: 5.
    V: 0.
numerics:
    dt: 1.e-10
    maxIt: 100
    numFlux: LW
    freq: 1
    periodicX: 1
    periodicY: 1
material:
    mu: 0.0794
    P0: 101325
    rho0: 877.7007
    T0: 323.15
    s: 0.0
