options:
    output: data/parabolic_slider_2d_deform_energy
    write_freq: 5
    save_output: False
    residual_analysis: True

grid:
    Lx: 0.1
    Ly: 0.1
    Nx: 50
    Ny: 50
    xE: ['D', 'N', 'N']
    xW: ['D', 'N', 'N']
    yS: ['D', 'N', 'N']
    yN: ['D', 'N', 'N']
    xE_D: 1.1853
    xW_D: 1.1853
    yS_D: 1.1853
    yN_D: 1.1853

geometry:
    type: parabolic_2d
    hmax: 6.6e-5
    hmin: 1.0e-5
    U: 50.
    V: 0.

numerics:
    solver: fem
    dt: 1.
    tol: 1e-10
    max_it: 50

properties:
    EOS: PL
    shear: 1.846e-5
    bulk: 0.
    P0: 101325
    rho0: 1.1853
    alpha: 0.
    elastic:
        E: 1e07
        v: 0.3
        alpha_underrelax: 0.1
        reference_point: [0,25]

fem_solver:
    linear_solver: iterative
    max_iter: 1
    R_norm_tol: 1e-09
    pspg_boundary_decay: 2.0
    physics:
        energy: True
        pspg: true
        gls: true

energy_spec:
    T0: 300.
    T_wall: 300.
    bc_xW: 'D'
    bc_xE: 'N'
    bc_yS: 'N'
    bc_yN: 'N'
    T_bc_xW: 300.
