options:
    output: data/parabolic_slider
    write_freq: 1000
    save_output: False
    residual_analysis: True

grid:
    Lx: 0.0762
    Ly: 0.01
    Nx: 100
    Ny: 10
    xE: ['D', 'N', 'N']
    xW: ['D', 'N', 'N']
    yS: ['P', 'P', 'P']
    yN: ['P', 'P', 'P']
    xE_D: 850.
    xW_D: 850.

geometry:
    type: parabolic
    hmin: 2.54e-5
    hmax: 5.08e-5
    U: 4.57
    V: 0.

numerics:
    solver: fem
    dt: 10.
    tol: 1e-08
    max_it: 10

properties:
    EOS: DH
    shear: 0.039
    bulk: 0.
    P0: 101325
    rho0: 850.
    C1: 3.5e10
    C2: 1.23

fem_solver:
    type: newton_alpha
    R_norm_tol: 1e-04
    max_iter: 10
    pspg_boundary_decay: 2.0
    physics:
        pspg: true
        gls: true
