name: CI

on: workflow_dispatch

# on:
#   push:
#     branches:
#       - publish
#     tags:
#       - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install_python
      run: |
        sudo apt-get update -qy
        sudo apt-get install -y python3-dev python3-pip libxml2-dev libxslt-dev zlib1g-dev libfftw3-dev libopenblas-dev
        sudo pip3 install setuptools
        sudo pip3 install -r requirements.txt
    - name: build
      run: |
        python3 setup.py install
    - name: Test with pytest
      run: |
        pytest

    #
    # - name: Publish package
    #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     user: __token__
    #     password: ${{ secrets.pypi_password }}
